function RTW_rtwnameSIDMap() {
	this.rtwnameHashMap = new Array();
	this.sidHashMap = new Array();
	this.rtwnameHashMap["<Root>"] = {sid: "A_Simple_Calculator"};
	this.sidHashMap["A_Simple_Calculator"] = {rtwname: "<Root>"};
	this.rtwnameHashMap["<S1>"] = {sid: "A_Simple_Calculator:11"};
	this.sidHashMap["A_Simple_Calculator:11"] = {rtwname: "<S1>"};
	this.rtwnameHashMap["<Root>/Input"] = {sid: "A_Simple_Calculator:9"};
	this.sidHashMap["A_Simple_Calculator:9"] = {rtwname: "<Root>/Input"};
	this.rtwnameHashMap["<Root>/Input1"] = {sid: "A_Simple_Calculator:10"};
	this.sidHashMap["A_Simple_Calculator:10"] = {rtwname: "<Root>/Input1"};
	this.rtwnameHashMap["<Root>/A simple Calculator"] = {sid: "A_Simple_Calculator:11"};
	this.sidHashMap["A_Simple_Calculator:11"] = {rtwname: "<Root>/A simple Calculator"};
	this.rtwnameHashMap["<Root>/ADD"] = {sid: "A_Simple_Calculator:21"};
	this.sidHashMap["A_Simple_Calculator:21"] = {rtwname: "<Root>/ADD"};
	this.rtwnameHashMap["<Root>/Sum "] = {sid: "A_Simple_Calculator:22"};
	this.sidHashMap["A_Simple_Calculator:22"] = {rtwname: "<Root>/Sum "};
	this.rtwnameHashMap["<Root>/Mul "] = {sid: "A_Simple_Calculator:23"};
	this.sidHashMap["A_Simple_Calculator:23"] = {rtwname: "<Root>/Mul "};
	this.rtwnameHashMap["<Root>/Div "] = {sid: "A_Simple_Calculator:24"};
	this.sidHashMap["A_Simple_Calculator:24"] = {rtwname: "<Root>/Div "};
	this.rtwnameHashMap["<S1>/In1"] = {sid: "A_Simple_Calculator:12"};
	this.sidHashMap["A_Simple_Calculator:12"] = {rtwname: "<S1>/In1"};
	this.rtwnameHashMap["<S1>/In2"] = {sid: "A_Simple_Calculator:13"};
	this.sidHashMap["A_Simple_Calculator:13"] = {rtwname: "<S1>/In2"};
	this.rtwnameHashMap["<S1>/Add"] = {sid: "A_Simple_Calculator:1"};
	this.sidHashMap["A_Simple_Calculator:1"] = {rtwname: "<S1>/Add"};
	this.rtwnameHashMap["<S1>/Divide"] = {sid: "A_Simple_Calculator:8"};
	this.sidHashMap["A_Simple_Calculator:8"] = {rtwname: "<S1>/Divide"};
	this.rtwnameHashMap["<S1>/Multiply"] = {sid: "A_Simple_Calculator:7"};
	this.sidHashMap["A_Simple_Calculator:7"] = {rtwname: "<S1>/Multiply"};
	this.rtwnameHashMap["<S1>/Subtract"] = {sid: "A_Simple_Calculator:6"};
	this.sidHashMap["A_Simple_Calculator:6"] = {rtwname: "<S1>/Subtract"};
	this.rtwnameHashMap["<S1>/Out1"] = {sid: "A_Simple_Calculator:14"};
	this.sidHashMap["A_Simple_Calculator:14"] = {rtwname: "<S1>/Out1"};
	this.rtwnameHashMap["<S1>/Out2"] = {sid: "A_Simple_Calculator:15"};
	this.sidHashMap["A_Simple_Calculator:15"] = {rtwname: "<S1>/Out2"};
	this.rtwnameHashMap["<S1>/Out3"] = {sid: "A_Simple_Calculator:16"};
	this.sidHashMap["A_Simple_Calculator:16"] = {rtwname: "<S1>/Out3"};
	this.rtwnameHashMap["<S1>/Out4"] = {sid: "A_Simple_Calculator:17"};
	this.sidHashMap["A_Simple_Calculator:17"] = {rtwname: "<S1>/Out4"};
	this.getSID = function(rtwname) { return this.rtwnameHashMap[rtwname];}
	this.getRtwname = function(sid) { return this.sidHashMap[sid];}
}
RTW_rtwnameSIDMap.instance = new RTW_rtwnameSIDMap();
