function RTW_rtwnameSIDMap() {
	this.rtwnameHashMap = new Array();
	this.sidHashMap = new Array();
	this.rtwnameHashMap["<Root>"] = {sid: "A_Simple_Logic_Claculator"};
	this.sidHashMap["A_Simple_Logic_Claculator"] = {rtwname: "<Root>"};
	this.rtwnameHashMap["<S1>"] = {sid: "A_Simple_Logic_Claculator:11"};
	this.sidHashMap["A_Simple_Logic_Claculator:11"] = {rtwname: "<S1>"};
	this.rtwnameHashMap["<Root>/Input"] = {sid: "A_Simple_Logic_Claculator:8"};
	this.sidHashMap["A_Simple_Logic_Claculator:8"] = {rtwname: "<Root>/Input"};
	this.rtwnameHashMap["<Root>/Input1"] = {sid: "A_Simple_Logic_Claculator:9"};
	this.sidHashMap["A_Simple_Logic_Claculator:9"] = {rtwname: "<Root>/Input1"};
	this.rtwnameHashMap["<Root>/Subsystem"] = {sid: "A_Simple_Logic_Claculator:11"};
	this.sidHashMap["A_Simple_Logic_Claculator:11"] = {rtwname: "<Root>/Subsystem"};
	this.rtwnameHashMap["<Root>/Out1"] = {sid: "A_Simple_Logic_Claculator:10"};
	this.sidHashMap["A_Simple_Logic_Claculator:10"] = {rtwname: "<Root>/Out1"};
	this.rtwnameHashMap["<S1>/In1"] = {sid: "A_Simple_Logic_Claculator:12"};
	this.sidHashMap["A_Simple_Logic_Claculator:12"] = {rtwname: "<S1>/In1"};
	this.rtwnameHashMap["<S1>/In2"] = {sid: "A_Simple_Logic_Claculator:13"};
	this.sidHashMap["A_Simple_Logic_Claculator:13"] = {rtwname: "<S1>/In2"};
	this.rtwnameHashMap["<S1>/AND"] = {sid: "A_Simple_Logic_Claculator:1"};
	this.sidHashMap["A_Simple_Logic_Claculator:1"] = {rtwname: "<S1>/AND"};
	this.rtwnameHashMap["<S1>/NOT"] = {sid: "A_Simple_Logic_Claculator:5"};
	this.sidHashMap["A_Simple_Logic_Claculator:5"] = {rtwname: "<S1>/NOT"};
	this.rtwnameHashMap["<S1>/NOT1"] = {sid: "A_Simple_Logic_Claculator:7"};
	this.sidHashMap["A_Simple_Logic_Claculator:7"] = {rtwname: "<S1>/NOT1"};
	this.rtwnameHashMap["<S1>/OR"] = {sid: "A_Simple_Logic_Claculator:2"};
	this.sidHashMap["A_Simple_Logic_Claculator:2"] = {rtwname: "<S1>/OR"};
	this.rtwnameHashMap["<S1>/XOR"] = {sid: "A_Simple_Logic_Claculator:3"};
	this.sidHashMap["A_Simple_Logic_Claculator:3"] = {rtwname: "<S1>/XOR"};
	this.rtwnameHashMap["<S1>/XOR1"] = {sid: "A_Simple_Logic_Claculator:6"};
	this.sidHashMap["A_Simple_Logic_Claculator:6"] = {rtwname: "<S1>/XOR1"};
	this.rtwnameHashMap["<S1>/Out1"] = {sid: "A_Simple_Logic_Claculator:14"};
	this.sidHashMap["A_Simple_Logic_Claculator:14"] = {rtwname: "<S1>/Out1"};
	this.rtwnameHashMap["<S1>/Out2"] = {sid: "A_Simple_Logic_Claculator:15"};
	this.sidHashMap["A_Simple_Logic_Claculator:15"] = {rtwname: "<S1>/Out2"};
	this.rtwnameHashMap["<S1>/Out3"] = {sid: "A_Simple_Logic_Claculator:16"};
	this.sidHashMap["A_Simple_Logic_Claculator:16"] = {rtwname: "<S1>/Out3"};
	this.rtwnameHashMap["<S1>/Out4"] = {sid: "A_Simple_Logic_Claculator:17"};
	this.sidHashMap["A_Simple_Logic_Claculator:17"] = {rtwname: "<S1>/Out4"};
	this.rtwnameHashMap["<S1>/Out5"] = {sid: "A_Simple_Logic_Claculator:18"};
	this.sidHashMap["A_Simple_Logic_Claculator:18"] = {rtwname: "<S1>/Out5"};
	this.getSID = function(rtwname) { return this.rtwnameHashMap[rtwname];}
	this.getRtwname = function(sid) { return this.sidHashMap[sid];}
}
RTW_rtwnameSIDMap.instance = new RTW_rtwnameSIDMap();
